package randomizer;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import java.util.Iterator;

public class populateMaps {
	
public static void main(String[] args) {
	//map of every character, with assigned numbers for eventually randomization
	HashMap<Integer, godClass> fullGodList = new HashMap<Integer, godClass>();
	//creates an object of each character, then places them within the map so each object's traits can be accessed
	Achilles achilles = new Achilles();
	fullGodList.put(1, achilles);
	Agni agni = new Agni();
	fullGodList.put(2,agni);
	Ah_Muzen_Cab amc = new Ah_Muzen_Cab();
	fullGodList.put(3,amc);
	Ah_Puch ahpuch = new Ah_Puch();
	fullGodList.put(4,ahpuch);
	Amaterasu ama = new Amaterasu();
	fullGodList.put(5,ama);
	Anhur anhur = new Anhur();
	fullGodList.put(6,anhur);
	Anubis anubis = new Anubis();
	fullGodList.put(7,anubis);
	Ao_Kuang aokuang = new Ao_Kuang();
	fullGodList.put(8, aokuang);
	Aphrodite aphro = new Aphrodite();
	fullGodList.put(9,aphro);
	Apollo apollo = new Apollo();
	fullGodList.put(10,apollo);
	Arachne arachne = new Arachne();
	fullGodList.put(11,arachne);
	Ares ares = new Ares();
	fullGodList.put(12,ares);
	Artemis artemis = new Artemis();
	fullGodList.put(13,artemis);
	Artio artio = new Artio();
	fullGodList.put(14,artio);
	Athena athena = new Athena();
	fullGodList.put(15,athena);
	Atlas atlas = new Atlas();
	fullGodList.put(16,atlas);
	Awilix awilix = new Awilix();
	fullGodList.put(17,awilix);
	Baba_Yaga baba = new Baba_Yaga();
	fullGodList.put(18,baba);
	Bacchus bacchus = new Bacchus();
	fullGodList.put(19,bacchus);
	Bakasura baka = new Bakasura();
	fullGodList.put(20,baka);
	Bake_Kujira bake = new Bake_Kujira();
	fullGodList.put(21,bake);
	Baron_Samedi baron = new Baron_Samedi();
	fullGodList.put(22,baron);
	Bastet bastet = new Bastet();
	fullGodList.put(23,bastet);
	Bellona bellona = new Bellona();
	fullGodList.put(24,bellona);
	Cabrakan cabrakan = new Cabrakan();
	fullGodList.put(25,cabrakan);
	Camazotz cama = new Camazotz();
	fullGodList.put(26,cama);
	Cerberus cerb = new Cerberus();
	fullGodList.put(27,cerb);
	Cernunnos cern = new Cernunnos();
	fullGodList.put(28,cern);
	Chaac chaac = new Chaac();
	fullGodList.put(29,chaac);
	Chang_e change = new Chang_e();
	fullGodList.put(30,change);
	Charon charon = new Charon();
	fullGodList.put(31,charon);
	Charybdis cherry = new Charybdis();
	fullGodList.put(32,cherry);
	Chernobog cherno = new Chernobog();
	fullGodList.put(33,cherno);
	Chiron chiron = new Chiron();
	fullGodList.put(34,chiron);
	Chronos chronos = new Chronos();
	fullGodList.put(35,chronos);
	Cliodhna clio = new Cliodhna();
	fullGodList.put(36,clio);
	Cthulhu cthu = new Cthulhu();
	fullGodList.put(37,cthu);
	Cu_Chulainn cuchu = new Cu_Chulainn();
	fullGodList.put(38,cuchu);
	Cupid cupid = new Cupid();
	fullGodList.put(39,cupid);
	Da_Ji daji = new Da_Ji();
	fullGodList.put(40,daji);
	Danzaburou danza = new Danzaburou();
	fullGodList.put(41,danza);
	Discordia discord = new Discordia();
	fullGodList.put(42,discord);
	Erlang_Shen erlang = new Erlang_Shen();
	fullGodList.put(43,erlang);
	Eset eset = new Eset();
	fullGodList.put(44,eset);
	Fafnir fafnir = new Fafnir();
	fullGodList.put(45,fafnir);
	Fenrir fenrir = new Fenrir();
	fullGodList.put(46,fenrir);
	Freya freya = new Freya();
	fullGodList.put(47,freya);
	Ganesha ganesha = new Ganesha();
	fullGodList.put(48,ganesha);
	Geb geb = new Geb();
	fullGodList.put(49,geb);
	Gilgamesh gilga = new Gilgamesh();
	fullGodList.put(50,gilga);
	Guan_Yu guan = new Guan_Yu();
	fullGodList.put(51,guan);
	Hachiman hachi = new Hachiman();
	fullGodList.put(52,hachi);
	Hades hades = new Hades();
	fullGodList.put(53,hades);
	He_Bo hebo = new He_Bo();
	fullGodList.put(54,hebo);
	Heimdallr heim = new Heimdallr();
	fullGodList.put(55,heim);
	Hel hel = new Hel();
	fullGodList.put(56,hel);
	Hera hera = new Hera();
	fullGodList.put(57,hera);
	Hercules herc = new Hercules();
	fullGodList.put(58,herc);
	Horus horus = new Horus();
	fullGodList.put(59,horus);
	Hou_Yi houyi = new Hou_Yi();
	fullGodList.put(60,houyi);
	Hun_Batz hun = new Hun_Batz();
	fullGodList.put(61,hun);
	Ishtar ishtar = new Ishtar();
	fullGodList.put(62,ishtar);
	Ix_Chel chel = new Ix_Chel();
	fullGodList.put(63,chel);
	Izanami iza = new Izanami();
	fullGodList.put(64,iza);
	Janus janus = new Janus();
	fullGodList.put(65,janus);
	Jing_Wei jing = new Jing_Wei();
	fullGodList.put(66,jing);
	Jormungandr jorm = new Jormungandr();
	fullGodList.put(67,jorm);
	Kali kali = new Kali();
	fullGodList.put(68,kali);
	Khepri khepri = new Khepri();
	fullGodList.put(69,khepri);
	King_Arthur king = new King_Arthur();
	fullGodList.put(70,king);
	Kukulkan kuku = new Kukulkan();
	fullGodList.put(71,kuku);
	Kumbhakarna kumba = new Kumbhakarna();
	fullGodList.put(72,kumba);
	Kuzenbo kuzenbo = new Kuzenbo();
	fullGodList.put(73,kuzenbo);
	Lancelot lance = new Lancelot();
	fullGodList.put(74,lance);
	Loki loki = new Loki();
	fullGodList.put(75,loki);
	Maman_Brigitte maman = new Maman_Brigitte();
	fullGodList.put(76,maman);
	Martichoras marti = new Martichoras();
	fullGodList.put(77,marti);
	Maui maui = new Maui();
	fullGodList.put(78,maui);
	Medusa medusa = new Medusa();
	fullGodList.put(79,medusa);
	Mercury merc = new Mercury();
	fullGodList.put(80,merc);
	Merlin merlin = new Merlin();
	fullGodList.put(81,merlin);
	Morgan_Le_Fay morgan = new Morgan_Le_Fay();
	fullGodList.put(82,morgan);
	Mulan mulan = new Mulan();
	fullGodList.put(83,mulan);
	Ne_Zha nezha = new Ne_Zha();
	fullGodList.put(84,nezha);
	Neith neith = new Neith();
	fullGodList.put(85,neith);
	Nemesis nem = new Nemesis();
	fullGodList.put(86,nem);
	Nike nike = new Nike();
	fullGodList.put(87,nike);
	Nox nox = new Nox();
	fullGodList.put(88,nox);
	Nu_Wa nuwa = new Nu_Wa();
	fullGodList.put(89,nuwa);
	Odin odin = new Odin();
	fullGodList.put(90,odin);
	Olorun olo = new Olorun();
	fullGodList.put(91,olo);
	Osiris osiris = new Osiris();
	fullGodList.put(92,osiris);
	Pele pele = new Pele();
	fullGodList.put(93,pele);
	Persephone perse = new Persephone();
	fullGodList.put(94,perse);
	Poseidon poe = new Poseidon();
	fullGodList.put(95,poe);
	Ra ra = new Ra();
	fullGodList.put(96,ra);
	Raijin raijin = new Raijin();
	fullGodList.put(97,raijin);
	Rama rama = new Rama();
	fullGodList.put(98,rama);
	Ratatoskr rat = new Ratatoskr();
	fullGodList.put(99,rat);
	Ravana ravana = new Ravana();
	fullGodList.put(100,ravana);
	Scylla scylla = new Scylla();
	fullGodList.put(101,scylla);
	Serqet serq = new Serqet();
	fullGodList.put(102,serq);
	Set2 set2 = new Set2();
	fullGodList.put(103,set2);
	Shiva shiva = new Shiva();
	fullGodList.put(104,shiva);
	Skadi skadi = new Skadi();
	fullGodList.put(105,skadi);
	Sobek sobek = new Sobek();
	fullGodList.put(106,sobek);
	Sol sol = new Sol();
	fullGodList.put(107,sol);
	Sun_Wukong sun = new Sun_Wukong();
	fullGodList.put(108,sun);
	Surtr surtr = new Surtr();
	fullGodList.put(109,surtr);
	Susano sus = new Susano();
	fullGodList.put(110,sus);
	Sylvanus syl = new Sylvanus();
	fullGodList.put(111,syl);
	Terra terra = new Terra();
	fullGodList.put(112,terra);
	Thanatos thana = new Thanatos();
	fullGodList.put(113,thana);
	The_Morrigan morri = new The_Morrigan();
	fullGodList.put(114,morri);
	Thor thor = new Thor();
	fullGodList.put(115,thor);
	Thoth thoth = new Thoth();
	fullGodList.put(116,thoth);
	Tiamat tiamat = new Tiamat();
	fullGodList.put(117,tiamat);
	Tsukuyomi tsu = new Tsukuyomi();
	fullGodList.put(118,tsu);
	Tyr tyr = new Tyr();
	fullGodList.put(119,tyr);
	Ullr ullr = new Ullr();
	fullGodList.put(120,ullr);
	Vamana vamana = new Vamana();
	fullGodList.put(121,vamana);
	Vulcan vulcan = new Vulcan();
	fullGodList.put(122,vulcan);
	Xbalanque xbal = new Xbalanque();
	fullGodList.put(123,xbal);
	Xing_Tian xing = new Xing_Tian();
	fullGodList.put(124,xing);
	Yemoja yemoja = new Yemoja();
	fullGodList.put(125,yemoja);
	Ymir ymir = new Ymir();
	fullGodList.put(126,ymir);
	Yu_Huang yu = new Yu_Huang();
	fullGodList.put(127,yu);
	Zeus zeus = new Zeus();
	fullGodList.put(128,zeus);
	Zhong_Kui zhong = new Zhong_Kui();
	fullGodList.put(129,zhong);
	Nut nut = new Nut();
	fullGodList.put(130,nut);
	
	//Set fgl = fullGodList.entrySet();
	//Iterator it = fgl.iterator();
	
	//setting up a group for randomizing assassins
	HashMap<Integer, godClass> assassinList = new HashMap<Integer, godClass>();
	assassinList.put(1, arachne);
	assassinList.put(2, baka);
	assassinList.put(3, bastet);
	assassinList.put(4, awilix);
	assassinList.put(5, cama);
	assassinList.put(6, clio);
	assassinList.put(7, daji);
	assassinList.put(8, fenrir);
	assassinList.put(9, hun);
	assassinList.put(10, kali);
	assassinList.put(11, lance);
	assassinList.put(12, loki);
	assassinList.put(13, merc);
	assassinList.put(14, nezha);
	assassinList.put(15, nem);
	assassinList.put(16, pele);
	assassinList.put(17, rat);
	assassinList.put(18, ravana);
	assassinList.put(19, serq);
	assassinList.put(20, set2);
	assassinList.put(21, sus);
	assassinList.put(22, thana);
	assassinList.put(23, thor);
	assassinList.put(24, tsu);
	
	//setting up a group for randomizing junglers
	HashMap<Integer, godClass> jungleList = new HashMap<Integer, godClass>();
	jungleList.put(1, aokuang);
	jungleList.put(2, arachne);
	jungleList.put(3, baka);
	jungleList.put(4, bastet);
	jungleList.put(5, awilix);
	jungleList.put(6, cama);
	jungleList.put(7, clio);
	jungleList.put(8, daji);
	jungleList.put(9, fenrir);
	jungleList.put(10, hun);
	jungleList.put(11, kali);
	jungleList.put(12, lance);
	jungleList.put(13, loki);
	jungleList.put(14, maman);
	jungleList.put(15, merc);
	jungleList.put(16, nezha);
	jungleList.put(17, nem);
	jungleList.put(18, pele);
	jungleList.put(19, rat);
	jungleList.put(20, ravana);
	jungleList.put(21, serq);
	jungleList.put(22, set2);
	jungleList.put(23, sus);
	jungleList.put(24, thana);
	jungleList.put(25, thor);
	jungleList.put(26, tsu);
	jungleList.put(27, achilles);
	jungleList.put(28, ama);
	jungleList.put(29, cabrakan);
	jungleList.put(30, charon);
	jungleList.put(31, cthu);
	jungleList.put(32, hades);
	jungleList.put(33, hebo);
	jungleList.put(34, herc);
	jungleList.put(35, janus);
	jungleList.put(36, mulan);
	jungleList.put(37, odin);
	jungleList.put(38, osiris);
	jungleList.put(39, poe);
	jungleList.put(40, scylla);
	jungleList.put(41, sun);
	jungleList.put(42, surtr);
	jungleList.put(43, morri);
	jungleList.put(44, tyr);
	jungleList.put(45, ullr);
	jungleList.put(46, vamana);
	jungleList.put(47, ymir);
	
	//setting up a group for adcs
	HashMap<Integer, godClass> adcList = new HashMap<Integer, godClass>();
	adcList.put(1, amc);
	adcList.put(2, anhur);
	adcList.put(3, apollo);
	adcList.put(4, artemis);
	adcList.put(5, cern);
	adcList.put(6, cherry);
	adcList.put(7, cherno);
	adcList.put(8, chiron);
	adcList.put(9, chronos);
	adcList.put(10, cupid);
	adcList.put(11, danza);
	adcList.put(12, freya);
	adcList.put(13, heim);
	adcList.put(14, houyi);
	adcList.put(15, hachi);
	adcList.put(16, ishtar);
	adcList.put(17, iza);
	adcList.put(18, jing);
	adcList.put(19, marti);
	adcList.put(20, medusa);
	adcList.put(21, neith);
	adcList.put(22, olo);
	adcList.put(23, rama);
	adcList.put(24, skadi);
	adcList.put(25, sol);
	adcList.put(26, ullr);
	adcList.put(27, xbal);
	adcList.put(28, nut);
	adcList.put(29, poe);
	adcList.put(30, zhong);
	
	//setting up a group for hunters
	HashMap<Integer, godClass> hunterList = new HashMap<Integer, godClass>();
	hunterList.put(1, amc);
	hunterList.put(2, anhur);
	hunterList.put(3, apollo);
	hunterList.put(4, artemis);
	hunterList.put(5, cern);
	hunterList.put(6, cherry);
	hunterList.put(7, cherno);
	hunterList.put(8, chiron);
	hunterList.put(9, cupid);
	hunterList.put(10, danza);
	hunterList.put(11, heim);
	hunterList.put(12, houyi);
	hunterList.put(13, hachi);
	hunterList.put(14, ishtar);
	hunterList.put(15, iza);
	hunterList.put(16, jing);
	hunterList.put(17, marti);
	hunterList.put(18, medusa);
	hunterList.put(19, neith);
	hunterList.put(20, rama);
	hunterList.put(21, skadi);
	hunterList.put(22, ullr);
	hunterList.put(23, xbal);
	hunterList.put(24, nut);
	
	//setting up a group for warriors
	HashMap<Integer, godClass> warriorList = new HashMap<Integer, godClass>();
	warriorList.put(1, achilles);
	warriorList.put(2, ama);
	warriorList.put(3, bellona);
	warriorList.put(4, chaac);
	warriorList.put(5, cuchu);
	warriorList.put(6, erlang);
	warriorList.put(7, gilga);
	warriorList.put(8, guan);
	warriorList.put(9, herc);
	warriorList.put(10, horus);
	warriorList.put(11, king);
	warriorList.put(12, mulan);
	warriorList.put(13, nike);
	warriorList.put(14, odin);
	warriorList.put(15, osiris);
	warriorList.put(16, shiva);
	warriorList.put(17, sun);
	warriorList.put(18, surtr);
	warriorList.put(19, tyr);
	warriorList.put(20, vamana);
	
	//setting up a group for solos
	HashMap<Integer, godClass> soloList = new HashMap<Integer, godClass>();
	soloList.put(1, achilles);
	soloList.put(2, ama);
	soloList.put(3, bellona);
	soloList.put(4, chaac);
	soloList.put(5, cuchu);
	soloList.put(6, erlang);
	soloList.put(7, gilga);
	soloList.put(8, guan);
	soloList.put(9, herc);
	soloList.put(10, horus);
	soloList.put(11, king);
	soloList.put(12, mulan);
	soloList.put(13, nike);
	soloList.put(14, odin);
	soloList.put(15, osiris);
	soloList.put(16, shiva);
	soloList.put(17, sun);
	soloList.put(18, surtr);
	soloList.put(19, tyr);
	soloList.put(20, vamana);
	soloList.put(21, aphro);
	soloList.put(22, ares);
	soloList.put(23, artio);
	soloList.put(24, athena);
	soloList.put(25, bacchus);
	soloList.put(26, bake);
	soloList.put(27, baron);
	soloList.put(28, cabrakan);
	soloList.put(29, cama);
	soloList.put(30, cerb);
	soloList.put(31, change);
	soloList.put(32, charon);
	soloList.put(33, cthu);
	soloList.put(34, eset);
	soloList.put(35, fafnir);
	soloList.put(36, hades);
	soloList.put(37, hel);
	soloList.put(38, hera);
	soloList.put(39, jorm);
	soloList.put(40, kuzenbo);
	soloList.put(41, nem);
	soloList.put(42, nezha);
	soloList.put(43, perse);
	soloList.put(44, rat);
	soloList.put(45, ravana);
	soloList.put(46, serq);
	soloList.put(47, set2);
	soloList.put(48, sobek);
	soloList.put(49, syl);
	soloList.put(50, terra);
	soloList.put(51, thoth);
	soloList.put(52, tiamat);
	soloList.put(53, xing);
	soloList.put(54, yemoja);
	soloList.put(55, ymir);
	soloList.put(56, zhong);
	
	//setting a group for guardians
	HashMap<Integer, godClass> guardianList = new HashMap<Integer, godClass>();
	guardianList.put(1, ares);
	guardianList.put(2, artio);
	guardianList.put(3, athena);
	guardianList.put(4, atlas);
	guardianList.put(5, bacchus);
	guardianList.put(6, bake);
	guardianList.put(7, cabrakan);
	guardianList.put(8, cerb);
	guardianList.put(9, charon);
	guardianList.put(10, cthu);
	guardianList.put(11, fafnir);
	guardianList.put(12, ganesha);
	guardianList.put(13, geb);
	guardianList.put(14, jorm);
	guardianList.put(15, khepri);
	guardianList.put(16, kumba);
	guardianList.put(17, kuzenbo);
	guardianList.put(18, maui);
	guardianList.put(19, sobek);
	guardianList.put(20, syl);
	guardianList.put(21, terra);
	guardianList.put(22, xing);
	guardianList.put(23, yemoja);
	guardianList.put(24, ymir);
	
	//setting a  group for supports
	HashMap<Integer, godClass> supportList = new HashMap<Integer, godClass>();
	supportList.put(1, ares);
	supportList.put(2, artio);
	supportList.put(3, athena);
	supportList.put(4, atlas);
	supportList.put(5, bacchus);
	supportList.put(6, bake);
	supportList.put(7, cabrakan);
	supportList.put(8, cerb);
	supportList.put(9, charon);
	supportList.put(10, cthu);
	supportList.put(11, fafnir);
	supportList.put(12, ganesha);
	supportList.put(13, geb);
	supportList.put(14, jorm);
	supportList.put(15, khepri);
	supportList.put(16, kumba);
	supportList.put(17, kuzenbo);
	supportList.put(18, maui);
	supportList.put(19, sobek);
	supportList.put(20, syl);
	supportList.put(21, terra);
	supportList.put(22, xing);
	supportList.put(23, yemoja);
	supportList.put(24, ymir);
	supportList.put(25, ama);
	supportList.put(26, aphro);
	supportList.put(27, baron);
	supportList.put(28, change);
	supportList.put(29, erlang);
	supportList.put(30, eset);
	supportList.put(31, guan);
	supportList.put(32, hades);
	supportList.put(33, hel);
	supportList.put(34, hera);
	supportList.put(35, chel);
	supportList.put(36, horus);
	supportList.put(37, mulan);
	supportList.put(38, nem);
	supportList.put(39, nox);
	supportList.put(40, ra);
	supportList.put(41, serq);
	supportList.put(42, nezha);
	supportList.put(43, zhong);
	
	//setting a group for mages
	HashMap<Integer, godClass> mageList = new HashMap<Integer, godClass>();
	mageList.put(1, agni);
	mageList.put(2, ahpuch);
	mageList.put(3, anubis);
	mageList.put(4, aokuang);
	mageList.put(5, aphro);
	mageList.put(6, baba);
	mageList.put(7, baron);
	mageList.put(8, change);
	mageList.put(9, chronos);
	mageList.put(10, discord);
	mageList.put(11, eset);
	mageList.put(12, freya);
	mageList.put(13, hades);
	mageList.put(14, hebo);
	mageList.put(15, hel);
	mageList.put(16, hera);
	mageList.put(17, chel);
	mageList.put(18, janus);
	mageList.put(19, kuku);
	mageList.put(20, maman);
	mageList.put(21, merlin);
	mageList.put(22, morgan);
	mageList.put(23, nox);
	mageList.put(24, nuwa);
	mageList.put(25, olo);
	mageList.put(26, perse);
	mageList.put(27, poe);
	mageList.put(28, ra);
	mageList.put(29, raijin);
	mageList.put(30, scylla);
	mageList.put(31, sol);
	mageList.put(32, morri);
	mageList.put(33, thoth);
	mageList.put(34, tiamat);
	mageList.put(35, vulcan);
	mageList.put(36, yu);
	mageList.put(37, zeus);
	mageList.put(38, zhong);
	
	//setting a group for mid
	HashMap<Integer, godClass> midList = new HashMap<Integer, godClass>();
	midList.put(1, agni);
	midList.put(2, ahpuch);
	midList.put(3, anubis);
	midList.put(4, aokuang);
	midList.put(5, aphro);
	midList.put(6, baba);
	midList.put(7, baron);
	midList.put(8, change);
	midList.put(9, chronos);
	midList.put(10, discord);
	midList.put(11, eset);
	midList.put(12, freya);
	midList.put(13, hades);
	midList.put(14, hebo);
	midList.put(15, hel);
	midList.put(16, hera);
	midList.put(17, chel);
	midList.put(18, janus);
	midList.put(19, kuku);
	midList.put(20, maman);
	midList.put(21, merlin);
	midList.put(22, morgan);
	midList.put(23, nox);
	midList.put(24, nuwa);
	midList.put(25, olo);
	midList.put(26, perse);
	midList.put(27, poe);
	midList.put(28, ra);
	midList.put(29, raijin);
	midList.put(30, scylla);
	midList.put(31, sol);
	midList.put(32, morri);
	midList.put(33, thoth);
	midList.put(34, tiamat);
	midList.put(35, vulcan);
	midList.put(36, yu);
	midList.put(37, zeus);
	midList.put(38, zhong);
	midList.put(39, amc);
	midList.put(40, apollo);
	midList.put(41, cherno);
	midList.put(42, hachi);
	midList.put(43, heim);
	midList.put(44, jing);
	midList.put(45, marti);
	midList.put(46, medusa);
	midList.put(47, neith);
	midList.put(48, skadi);
	midList.put(49, ullr);
	}

	
	
}
